node {

    withMaven(maven:'localmaven') {

        stage('Checkout') {
            git url: 'https://github.com/bhai840/sample-spring-microservices.git', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('discovery-service') {
                   def registry = "rahulnallari/sample-spring-microservices"

                   def registryCredential = 'dockerhub'

                   def dockerImage = docker.build "${registry}:account${env.version}"

                   def latest = docker.build "${registry}:account_latest"

                   docker.withRegistry( '', registryCredential ) {
                             dockerImage.push()
                             latest.push()

                             }
            }
        }

    /*    stage ('Run') {
            docker.image("localhost:5000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        } */

        stage ('Final') {
            build job: 'gateway-service', wait: false
        }      

    }

}
